if SERVER then

    local function removeAllTaunts()
        for index, taunt in pairs(table.Copy(GAMEMODE.Hunter_Taunts)) do
            table.remove(GAMEMODE.Hunter_Taunts, index)
        end
        for index, taunt in pairs(table.Copy(GAMEMODE.Prop_Taunts)) do
            table.remove(GAMEMODE.Prop_Taunts, index)
        end
    end

    hook.Add("ph_AddTaunts", "kraboetauntpack_taunts", function()

        -- Delete all taunts that will be replaced by ours
        removeAllTaunts()

        -- Hunter taunts
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/1.mp3", "Still trying to win" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/2.mp3", "Gandalf" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/3.mp3", "A-team" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/4.mp3", "Attack on Titan" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/5.mp3", "Bad boys" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/6.mp3", "Bed intruder" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/7.mp3", "Booty Warrior" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/8.mp3", "MGS Found" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/9.mp3", "Ghostbusters" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/10.mp3", "Taken" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/11.mp3", "Fugees" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/12.mp3", "Whereareyou" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/13.mp3", "I'm Batman" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/14.mp3", "Surprise Mothafucka" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/15.mp3", "Bed Intruder Find you" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/16.mp3", "No Limit" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/17.mp3", "All around the world (la la la)" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/18.mp3", "Freestyler" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/19.mp3", "Get down on it" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/20.mp3", "Mortal Kombat" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/21.mp3", "Rakesh" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/22.mp3", "It wasn't me" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/23.mp3", "Come on and SLAM" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/24.mp3", "That's the way 1" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/25.mp3", "That's the way 2" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/26.mp3", "The bad touch" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/27.mp3", "You Lose" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/28.mp3", "Hallo klootviolen" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/29.mp3", "Did I break your concentration" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/30.mp3", "Snakes on a plane" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/31.mp3", "I'm Chris Hansen" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/32.mp3", "Love to taste you" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/33.mp3", "Say WHAT again" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/34.mp3", "Shut the fuck up fat man" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/35.mp3", "Shut the fuck up" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/36.mp3", "Surprise cockfags" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/37.mp3", "Till you tell me to stop" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/38.mp3", "You lose team america" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/39.mp3", "Smart motherfucker" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/40.mp3", "Warriors come out to play" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/41.mp3", "Opsporing verzocht G 1" })
        table.insert(GAMEMODE.Hunter_Taunts, { "taunts/kraboetauntpack/hunters/42.mp3", "Opsporing verzocht G 2" })

        -- Prop taunts
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/1.mp3", "Palm Jeruzalem" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/2.mp3", "Alles elektriciteit" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/3.mp3", "Bami" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/4.mp3", "Lenny" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/5.mp3", "Java Gamelan" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/6.mp3", "Annie Tibbers" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/7.mp3", "Liliane Fonds" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/8.mp3", "MK Baby Crying" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/9.mp3", "TOASTY" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/10.mp3", "Rick Roll" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/11.mp3", "Thomas the bitch engine" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/12.mp3", "Gamecube" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/13.mp3", "Get Hyper" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/14.mp3", "Deez nuts" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/15.mp3", "Dayum drops" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/16.mp3", "Banana phone" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/17.mp3", "Kishan Verjari" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/18.mp3", "Barrel roll" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/19.mp3", "Gangnam Style" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/20.mp3", "Gentleman" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/21.mp3", "GIGA PUDDI" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/22.mp3", "Ujala Bollywood Weekender" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/23.mp3", "WOMBO COMBO" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/24.mp3", "Tijdmachine" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/25.mp3", "Buma in mn zak" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/26.mp3", "Ujala jingle" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/27.mp3", "Mario dead" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/28.mp3", "Navi HEY" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/29.mp3", "Epic sax guy" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/30.mp3", "Air horn" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/31.mp3", "Smoke weed ERRDAY" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/32.mp3", "POKEYMANS" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/33.mp3", "Booty groceries" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/34.mp3", "Zoidberg" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/35.mp3", "YATTATATATAT" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/36.mp3", "Zelda secret" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/37.mp3", "Wryyyyy" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/38.mp3", "MUDAMUDA" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/39.mp3", "Yoga flame" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/40.mp3", "Yoga fire" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/41.mp3", "TIGER" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/42.mp3", "TIGER UPPERCUT" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/43.mp3", "What is love" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/44.mp3", "Say whaaaaaa" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/45.mp3", "I like turtles" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/46.mp3", "Bed Intruder hide yo kids" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/47.mp3", "Sonny" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/48.mp3", "Aye Wine" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/49.mp3", "In the air tonight" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/50.mp3", "Bailando" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/51.mp3", "Krishan 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/52.mp3", "Krishan 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/53.mp3", "Krishan 3" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/54.mp3", "Krishan 4" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/55.mp3", "Krishan 5" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/56.mp3", "Kont 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/57.mp3", "Kont 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/58.mp3", "Kont 3" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/59.mp3", "Kont 4" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/60.mp3", "Follow the leader" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/61.mp3", "Faziel Minirok" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/62.mp3", "Faziel Daroe" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/63.mp3", "Faluma" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/64.mp3", "Chop ma money" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/65.mp3", "Bobolist" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/66.mp3", "I love cats" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/67.mp3", "Bitch don't kill my vibe" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/68.mp3", "Turk AAAAAH" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/69.mp3", "Lovely day" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/70.mp3", "Daddy cool" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/71.mp3", "What's your flava" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/72.mp3", "Turk DEBIJEEEEE" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/73.mp3", "Turk FLIKKEEEER" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/74.mp3", "Turk HELPMEEEE" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/75.mp3", "Turk HIJ DOET MIJ PIJN" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/76.mp3", "HotHotHot 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/77.mp3", "HotHotHot 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/78.mp3", "HotHotHot 3" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/79.mp3", "Hotline Bling 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/80.mp3", "Hotline Bling 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/81.mp3", "Hotlines 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/82.mp3", "Hotlines 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/83.mp3", "Turk IKVERGEETDITNIET" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/84.mp3", "Kutkind 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/85.mp3", "Kutkind 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/86.mp3", "Kutkind 3" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/87.mp3", "Kutkind 4" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/88.mp3", "Kutkind 5" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/89.mp3", "Kutkind 6" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/90.mp3", "Isrealites 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/91.mp3", "Isrealites 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/92.mp3", "Bomba" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/93.mp3", "IK BETAAL NIKS" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/94.mp3", "Zinloos" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/95.mp3", "My name Jeff" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/96.mp3", "X-Files" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/97.mp3", "Kempi diss 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/98.mp3", "Kempi diss 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/99.mp3", "Purple Rain" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/100.mp3", "Tempted to touch" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/101.mp3", "Opposites South Africa" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/102.mp3", "Opposites Dom Lomp en Famous" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/103.mp3", "Banana Light 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/104.mp3", "Banana Light 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/105.mp3", "Zsa Zsa Su" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/106.mp3", "Amberlamps" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/107.mp3", "Leave Britney alone" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/108.mp3", "OOH BABY A TRIPLE" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/109.mp3", "Ay ay chico" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/110.mp3", "Your team has destroyed a turret ayy lmao" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/111.mp3", "Indian vocal" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/112.mp3", "Native 1" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/113.mp3", "Native 2" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/114.mp3", "Rick Bami" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/115.mp3", "ROAD ROLLER DA" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/116.mp3", "Shwili shwili" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/117.mp3", "Teleweni" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/118.mp3", "Vho war cry" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/119.mp3", "Arab yalalala" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/120.mp3", "Woes" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/121.mp3", "Where you at fam" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/122.mp3", "tprprprpepelaaaa" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/123.mp3", "Super MLG Mario" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/124.mp3", "Skype" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/125.mp3", "Ik dacht NEEEEE" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/126.mp3", "Laterrrrr" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/127.mp3", "Klootviool wat doe je" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/128.mp3", "Faka zeus" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/129.mp3", "Eehman peukie roken" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/130.mp3", "Da village people" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/131.mp3", "Check je later homies for life" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/132.mp3", "Born to be alive" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/133.mp3", "Bami mia mia" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/134.mp3", "Bami 2.0" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/135.mp3", "Babi panpang in je reet" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/136.mp3", "AYYY FAM" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/137.mp3", "Vince from shamwow" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/138.mp3", "MATT DAMON" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/139.mp3", "You'll be saying wow" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/140.mp3", "When we were young" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/141.mp3", "Don't take away the music" })
        table.insert(GAMEMODE.Prop_Taunts, { "taunts/kraboetauntpack/props/142.mp3", "Watskeburt" })

    end )
end